- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
      files: ^console/
      # exclude: >
      #     (?x)^(
      #         www/apiclient/regionapi.py|
      #         console/views/app_manage.py|
      #         console/services/app_config/port_service.py|
      #         console/services/app.py|
      #         www/tenantservice/baseservice.py|
      #         goodrain_web/test_settings.py|
      #         ^backends/
      #     )$
    - id: check-docstring-first
    - id: debug-statements
    
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
    - id: reorder-python-imports
      language_version: python2.7
