- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
      exclude: >
          (?x)^(
              console/views/app_manage.py
          )$
    - id: check-docstring-first
    - id: debug-statements
    
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
    - id: reorder-python-imports
      language_version: python2.7
